import { Project } from "@/types";

export const mockProjects: Project[] = [
  {
    id: "1",
    slug: "agrochain-ai",
    name: "AgroChain AI",
    tagline: "Çiftçileri DeFi ile buluşturan yapay zeka destekli tarım finansmanı",
    description: "AgroChain AI, Türkiye'deki küçük ölçekli çiftçilerin finansmana erişimini demokratikleştiriyor. Geleneksel bankacılık sistemine erişimi olmayan 3 milyon çiftçiyi hedefliyoruz. Yapay zeka destekli kredi skorlama modelimiz, toprak kalitesi, hava durumu verileri ve geçmiş hasat kayıtlarını analiz ederek çiftçilere adil ve hızlı finansman sağlıyor. Stellar ağı üzerinde çalışan akıllı kontratlarımız, aracıları ortadan kaldırarak çiftçilerin doğrudan yatırımcılarla buluşmasını sağlıyor.",
    howItWorks: "Çiftçi platforma kayıt olup arazi bilgilerini giriyor. Yapay zeka modelimiz uydu görüntüleri, toprak sensörleri ve hava durumu verilerini analiz ederek kredi skoru oluşturuyor. Soroban akıllı kontratı, hasat döneminde otomatik geri ödeme tetikliyor. Yatırımcılar milestone bazlı olarak fonlarını serbest bırakıyor, her aşama tamamlandığında akıllı kontrat doğrulayıp bir sonraki dilimi açıyor.",
    category: "AI/ML",
    emoji: "🌾",
    coverImage: "/covers/agrochain.jpg",
    raised: 38500,
    goal: 50000,
    backers: 127,
    daysLeft: 14,
    featured: true,
    owner: "GCWV...XK42",
    tags: ["Agriculture", "AI", "DeFi", "Impact"],
    createdAt: "2026-09-01",
    pitchDeckUrl: "https://pitch.com/agrochain",
    team: [
      { name: "Ahmet Yıldız", role: "CEO & Co-founder", avatar: "AY", linkedin: "#" },
      { name: "Selin Kaya", role: "CTO & Blockchain Lead", avatar: "SK", linkedin: "#" },
      { name: "Burak Demir", role: "AI/ML Engineer", avatar: "BD", linkedin: "#" },
    ],
    milestones: [
      { id: "m1", title: "MVP Geliştirme", description: "Temel platform altyapısı ve akıllı kontratlar", targetAmount: 15000, completed: true, date: "2026-08-15" },
      { id: "m2", title: "Beta Lansmanı", description: "100 pilot çiftçi ile canlı test", targetAmount: 25000, completed: true, date: "2026-09-01" },
      { id: "m3", title: "Ölçeklendirme", description: "1000 çiftçiye genişleme ve mobil uygulama", targetAmount: 50000, completed: false, date: "2026-11-01" },
    ],
  },
  {
    id: "2",
    slug: "medisync-chain",
    name: "MediSync Chain",
    tagline: "Hasta verilerinin egemenliğini hastaya veren sağlık blockchain'i",
    description: "MediSync Chain, sağlık kayıtlarını merkeziyetsizleştirerek hastaların kendi tıbbi verilerinin tam kontrolünü elinde tutmasını sağlıyor. Farklı hastaneler ve klinikler arasında güvenli, anonim veri paylaşımı yapılabiliyor. Hasta, hangi doktora hangi kaydını açacağını tam kontrol ediyor.",
    howItWorks: "Hasta tıbbi kayıtları şifrelenerek IPFS'e yükleniyor, erişim anahtarı Stellar ağında saklanıyor. Doktor erişim talep ettiğinde hasta mobil uygulamadan onay veriyor. Veri paylaşımı karşılığında hasta araştırmacı kuruluşlara anonim veri satabiliyor. Tüm erişim logları değiştirilemez biçimde blockchain'e kaydediliyor.",
    category: "HealthTech",
    emoji: "🏥",
    coverImage: "/covers/medisync.jpg",
    raised: 22000,
    goal: 75000,
    backers: 89,
    daysLeft: 21,
    featured: false,
    owner: "GBMN...PQ91",
    tags: ["Healthcare", "Privacy", "Web3"],
    createdAt: "2026-09-05",
    team: [
      { name: "Dr. Emre Şahin", role: "CEO & Medical Advisor", avatar: "ES", linkedin: "#" },
      { name: "Zeynep Arslan", role: "Full-stack Developer", avatar: "ZA", linkedin: "#" },
      { name: "Okan Yücel", role: "Cybersecurity Expert", avatar: "OY", linkedin: "#" },
    ],
    milestones: [
      { id: "m1", title: "Protokol Tasarımı", description: "HIPAA uyumlu veri şifreleme protokolü", targetAmount: 20000, completed: true, date: "2026-08-20" },
      { id: "m2", title: "Pilot Hastane", description: "3 hastane ile pilot entegrasyon", targetAmount: 45000, completed: false, date: "2026-10-15" },
      { id: "m3", title: "Ulusal Ölçek", description: "Türkiye geneli yaygınlaştırma", targetAmount: 75000, completed: false, date: "2026-12-01" },
    ],
  },
  {
    id: "3",
    slug: "edufund-dao",
    name: "EduFund DAO",
    tagline: "Öğrenci burslarını merkeziyetsizleştiren topluluk yönetimli fon",
    description: "EduFund DAO, yükseköğrenim burslarını şeffaf ve topluluk yönetimli bir yapıya kavuşturuyor. Token sahipleri, burs adaylarını oylamayla seçiyor ve fonların etkin kullanımını denetliyor. Stellar ağındaki akıllı kontratlar sayesinde burslar otomatik olarak dağıtılıyor.",
    howItWorks: "Öğrenciler DAO'ya başvuru yapıyor, akademik başarı ve proje planlarını sunuyor. Token sahipleri 1 haftalık oylama sürecinde adayları değerlendiriyor. Seçilen öğrencilere burs, okul dönemlerine göre otomatik ödeniyor. Öğrenci mezun olduğunda opsiyonel geri katkı mekanizmasıyla ekosistem büyüyor.",
    category: "EdTech",
    emoji: "🎓",
    coverImage: "/covers/edufund.jpg",
    raised: 91200,
    goal: 100000,
    backers: 312,
    daysLeft: 7,
    featured: true,
    owner: "GDAM...RT55",
    tags: ["Education", "DAO", "Scholarships"],
    createdAt: "2026-08-20",
    team: [
      { name: "Merve Toprak", role: "Founder & Product Lead", avatar: "MT", linkedin: "#" },
      { name: "Can Öztürk", role: "Smart Contract Developer", avatar: "CO", linkedin: "#" },
      { name: "Elif Yaman", role: "Community Manager", avatar: "EY", linkedin: "#" },
    ],
    milestones: [
      { id: "m1", title: "DAO Yapısı", description: "Governance token ve oylama mekanizması", targetAmount: 30000, completed: true, date: "2026-08-30" },
      { id: "m2", title: "İlk Burs Turu", description: "10 öğrenciye burs dağıtımı", targetAmount: 60000, completed: true, date: "2026-09-10" },
      { id: "m3", title: "Üniversite Ortaklıkları", description: "5 üniversite ile MOU imzalanması", targetAmount: 100000, completed: false, date: "2026-10-30" },
    ],
  },
  {
    id: "4",
    slug: "greenwatt-defi",
    name: "GreenWatt DeFi",
    tagline: "Güneş enerjisi üreticilerini yatırımcılarla doğrudan buluşturan platform",
    description: "GreenWatt DeFi, çatı güneş paneli sahiplerinin fazla elektrik üretimini tokenize ederek yatırımcılara satmasını sağlıyor. Her kWh bir token olarak temsil ediliyor ve Stellar ağında işlem görüyor.",
    howItWorks: "Güneş paneli sahibi sisteme akıllı sayaç verilerini bağlıyor. Fazla üretim otomatik olarak kWh token'a dönüşüyor. Yatırımcılar bu token'ları satın alarak enerji üretimine ortak oluyor. Aylık gelir USDC olarak token sahiplerine dağıtılıyor. TEDAŞ şebeke fiyatı referans alınarak akıllı kontrat fiyatı belirliyor.",
    category: "GreenTech",
    emoji: "☀️",
    coverImage: "/covers/greenwatt.jpg",
    raised: 14300,
    goal: 80000,
    backers: 54,
    daysLeft: 45,
    featured: false,
    owner: "GNWT...ZZ12",
    tags: ["Climate", "Energy", "Tokenization"],
    createdAt: "2026-09-10",
    team: [
      { name: "Kerem Avcı", role: "CEO", avatar: "KA" },
      { name: "İpek Güneş", role: "Energy Engineer", avatar: "İG" },
      { name: "Selim Ateş", role: "IoT Developer", avatar: "SA" },
    ],
    milestones: [
      { id: "m1", title: "Tokenizasyon Modeli", description: "kWh token standart protokolü", targetAmount: 20000, completed: false, date: "2026-10-01" },
      { id: "m2", title: "Pilot Mahalle", description: "İzmir'de 50 hanede pilot test", targetAmount: 50000, completed: false, date: "2026-11-15" },
      { id: "m3", title: "Ulusal Şebeke", description: "TEDAŞ ile entegrasyon", targetAmount: 80000, completed: false, date: "2027-01-01" },
    ],
  },
  {
    id: "5",
    slug: "paylink-stellar",
    name: "PayLink Stellar",
    tagline: "İşletmeler için saniyeler içinde cross-border ödeme altyapısı",
    description: "PayLink Stellar, küçük ve orta ölçekli işletmelerin uluslararası ödemelerini Stellar ağı üzerinden saniyeler içinde, minimum komisyonla gerçekleştirmesini sağlıyor. Mevcut SWIFT sistemine göre %90 daha hızlı ve %95 daha ucuz.",
    howItWorks: "İşletme API anahtarını alıp kendi sistemine entegre ediyor. Ödeme talebi Stellar path payment ile en uygun kur üzerinden gerçekleşiyor. Alıcı, kendi yerel para biriminde ödemeyi alıyor. Tüm işlem 3-5 saniye içinde tamamlanıyor. Aylık özet rapor ve muhasebe entegrasyonu ek olarak sunuluyor.",
    category: "DeFi",
    emoji: "💸",
    coverImage: "/covers/paylink.jpg",
    raised: 55000,
    goal: 60000,
    backers: 203,
    daysLeft: 3,
    featured: false,
    owner: "GPLK...MM88",
    tags: ["Payments", "B2B", "Cross-border"],
    createdAt: "2026-08-25",
    team: [
      { name: "Tolga Kılıç", role: "CEO & Fintech Expert", avatar: "TK" },
      { name: "Ayşe Nur Çelik", role: "Backend Engineer", avatar: "AN" },
      { name: "Murat Başaran", role: "Business Development", avatar: "MB" },
    ],
    milestones: [
      { id: "m1", title: "API Geliştirme", description: "RESTful ödeme API'si", targetAmount: 20000, completed: true, date: "2026-09-05" },
      { id: "m2", title: "Banka Entegrasyonu", description: "3 Türk bankası ile entegrasyon", targetAmount: 40000, completed: true, date: "2026-09-15" },
      { id: "m3", title: "AB Pazarı", description: "SEPA uyumlu AB ödemeleri", targetAmount: 60000, completed: false, date: "2026-10-20" },
    ],
  },
  {
    id: "6",
    slug: "craftdao",
    name: "CraftDAO",
    tagline: "Türk zanaatkarlarını küresel koleksiyonerlere bağlayan NFT pazaryeri",
    description: "CraftDAO, geleneksel Türk el sanatlarını (kilim, çini, bakır işleme) NFT olarak tokenize ediyor. Her eserin fiziksel sertifikası blockchain'de kayıtlı. Zanaatkarlar ikincil satışlardan da royalty alıyor.",
    howItWorks: "Zanaatkar eseri oluştururken QR kodlu sertifika alıyor. Eser fotoğrafları ve meta verileri IPFS'e yükleniyor, NFT basılıyor. Koleksiyoner NFT'yi satın aldığında fiziksel eserin teslimatı akıllı kontratla güvence altına alınıyor. Eser ikinci elden satıldığında zanaatkar otomatik %5 royalty kazanıyor.",
    category: "SaaS",
    emoji: "🏺",
    coverImage: "/covers/craftdao.jpg",
    raised: 8700,
    goal: 30000,
    backers: 41,
    daysLeft: 30,
    featured: false,
    owner: "GCFT...AA99",
    tags: ["NFT", "Culture", "Artisan"],
    createdAt: "2026-09-12",
    team: [
      { name: "Fatma Kıran", role: "Founder & Art Director", avatar: "FK" },
      { name: "Serdar Yıldırım", role: "NFT Developer", avatar: "SY" },
    ],
    milestones: [
      { id: "m1", title: "NFT Standart", description: "Fiziksel-dijital eser köprüsü protokolü", targetAmount: 10000, completed: false, date: "2026-10-10" },
      { id: "m2", title: "İlk Koleksiyon", description: "50 zanaatkar, 200 eser", targetAmount: 20000, completed: false, date: "2026-11-01" },
      { id: "m3", title: "Global Pazar", description: "Uluslararası koleksiyoner ağı", targetAmount: 30000, completed: false, date: "2026-12-15" },
    ],
  },
  {
    id: "7",
    slug: "studyfi",
    name: "StudyFi",
    tagline: "Öğrencilerin ders notlarını tokenize edip kazandığı bilgi ekonomisi platformu",
    description: "StudyFi, öğrencilerin kaliteli ders notlarını ve çalışma materyallerini token karşılığı paylaştığı bir bilgi ekonomisi platformu. Not kalitesi topluluk oylamasıyla belirleniyor, yüksek puanlı içerikler daha fazla kazandırıyor.",
    howItWorks: "Öğrenci ders notunu platforma yükliyor ve fiyat belirliyor. Alıcılar USDC ile içeriğe erişim satın alıyor. Topluluk oylamasıyla içerik kalite puanı yükselirse otomatik bonus ödüllendirilme gerçekleşiyor. Yazar, sonraki satışlardan da pasif gelir kazanmaya devam ediyor.",
    category: "EdTech",
    emoji: "📚",
    coverImage: "/covers/studyfi.jpg",
    raised: 12400,
    goal: 40000,
    backers: 76,
    daysLeft: 28,
    featured: false,
    owner: "GSTF...BB22",
    tags: ["Education", "Knowledge", "Earn"],
    createdAt: "2026-09-08",
    team: [
      { name: "Deniz Korkmaz", role: "Founder", avatar: "DK" },
      { name: "Arda Şimşek", role: "Product Designer", avatar: "AŞ" },
      { name: "Ceren Doğan", role: "Backend Dev", avatar: "CD" },
    ],
    milestones: [
      { id: "m1", title: "Platform MVP", description: "İçerik yükleme ve satın alma altyapısı", targetAmount: 12000, completed: true, date: "2026-09-05" },
      { id: "m2", title: "Topluluk Oylama", description: "Kalite değerlendirme sistemi", targetAmount: 25000, completed: false, date: "2026-10-20" },
      { id: "m3", title: "Üniversite Ortaklığı", description: "5 üniversite ile resmi içerik anlaşması", targetAmount: 40000, completed: false, date: "2026-12-01" },
    ],
  },
  {
    id: "8",
    slug: "carbon-ledger",
    name: "Carbon Ledger",
    tagline: "Şirketlerin karbon ayak izini blockchain'de şeffaf takip eden platform",
    description: "Carbon Ledger, kurumların karbon emisyonlarını Stellar blockchain üzerinde değiştirilemez biçimde kaydeden ve karbon kredi ticaretini kolaylaştıran bir platform. ESG raporlamasını otomatikleştiriyor.",
    howItWorks: "Şirket IoT sensörlerini veya manuel veri girişini platforma bağlıyor. Emisyon verileri blockchain'e kaydediliyor ve bağımsız doğrulayıcılar onaylıyor. Fazla karbon kredisi diğer şirketlere satılabiliyor. Yıllık ESG raporu otomatik oluşturuluyor ve denetçilere doğrulanabilir link paylaşılıyor.",
    category: "GreenTech",
    emoji: "🌿",
    coverImage: "/covers/carbon.jpg",
    raised: 31000,
    goal: 65000,
    backers: 98,
    daysLeft: 18,
    featured: false,
    owner: "GCBN...TT44",
    tags: ["ESG", "Carbon", "Sustainability"],
    createdAt: "2026-09-03",
    team: [
      { name: "Berk Yılmaz", role: "CEO", avatar: "BY" },
      { name: "Naz Çetin", role: "Environmental Engineer", avatar: "NÇ" },
      { name: "Furkan Şahin", role: "Blockchain Developer", avatar: "FŞ" },
    ],
    milestones: [
      { id: "m1", title: "Veri Protokolü", description: "Emisyon kayıt standardı", targetAmount: 20000, completed: true, date: "2026-09-01" },
      { id: "m2", title: "Doğrulayıcı Ağı", description: "Bağımsız denetçi entegrasyonu", targetAmount: 40000, completed: false, date: "2026-10-15" },
      { id: "m3", title: "Karbon Borsası", description: "P2P kredi ticareti platformu", targetAmount: 65000, completed: false, date: "2026-12-01" },
    ],
  },
  {
    id: "9",
    slug: "rentchain",
    name: "RentChain",
    tagline: "Kiracı ve ev sahiplerini güven sözleşmesiyle buluşturan kira platformu",
    description: "RentChain, kira sözleşmelerini akıllı kontratlara taşıyarak depozito anlaşmazlıklarını ortadan kaldırıyor. Kira ödemeleri otomatik, depozito ise tarafsız escrow'da tutuluyor.",
    howItWorks: "Ev sahibi ve kiracı sözleşme koşullarını platforma giriyor. Depozito Stellar escrow'a kilitlenir. Her ay kira otomatik ödeniyor, gecikme olursa akıllı kontrat uyarı gönderiyor. Çıkışta her iki taraf durumu onaylarsa depozito anında iade ediliyor, anlaşmazlıkta hakeme gönderiliyor.",
    category: "SaaS",
    emoji: "🏠",
    coverImage: "/covers/rentchain.jpg",
    raised: 19500,
    goal: 45000,
    backers: 63,
    daysLeft: 22,
    featured: false,
    owner: "GRNT...LL77",
    tags: ["RealEstate", "Escrow", "PropTech"],
    createdAt: "2026-09-07",
    team: [
      { name: "Yusuf Erdoğan", role: "CEO", avatar: "YE" },
      { name: "Sinem Aktaş", role: "Legal Tech Advisor", avatar: "SA" },
    ],
    milestones: [
      { id: "m1", title: "Sözleşme Şablonu", description: "Hukuki geçerliliği onaylı akıllı kontrat", targetAmount: 15000, completed: false, date: "2026-10-01" },
      { id: "m2", title: "Pilot Kiracılar", description: "50 aktif kira sözleşmesi", targetAmount: 30000, completed: false, date: "2026-11-01" },
      { id: "m3", title: "Hakem Sistemi", description: "Anlaşmazlık çözüm mekanizması", targetAmount: 45000, completed: false, date: "2026-12-15" },
    ],
  },
  {
    id: "10",
    slug: "healthtoken",
    name: "HealthToken",
    tagline: "Sağlıklı yaşam alışkanlıklarını ödüllendiren Web3 wellness platformu",
    description: "HealthToken, kullanıcıların günlük adım sayısı, uyku kalitesi ve diyet takibi gibi sağlık verilerini paylaşmaları karşılığında token kazandığı bir wellness platformu. Sağlık sigortacıları bu verilere anonim erişim için ödeme yapıyor.",
    howItWorks: "Kullanıcı akıllı saat veya telefon sensörlerini platforma bağlıyor. Günlük hedefler tamamlandığında HTK token kazanılıyor. Token'lar partner eczane ve spor salonu zincirlerinde kullanılabiliyor. Anonim toplam sağlık verisi sigorta şirketlerine satılıyor, gelir havuza aktarılarak kullanıcılara dağıtılıyor.",
    category: "HealthTech",
    emoji: "💪",
    coverImage: "/covers/healthtoken.jpg",
    raised: 27800,
    goal: 55000,
    backers: 144,
    daysLeft: 35,
    featured: false,
    owner: "GHLT...KK33",
    tags: ["Wellness", "Fitness", "Earn"],
    createdAt: "2026-09-06",
    team: [
      { name: "Gizem Yıldız", role: "Co-founder & Health Expert", avatar: "GY" },
      { name: "Ali Çelik", role: "Mobile Developer", avatar: "AÇ" },
      { name: "Hakan Kaya", role: "Data Scientist", avatar: "HK" },
    ],
    milestones: [
      { id: "m1", title: "Sensor Entegrasyonu", description: "Apple Health & Google Fit bağlantısı", targetAmount: 15000, completed: true, date: "2026-09-01" },
      { id: "m2", title: "Token Ekonomisi", description: "HTK token dağıtım mekanizması", targetAmount: 35000, completed: false, date: "2026-10-20" },
      { id: "m3", title: "Sigorta Ortaklığı", description: "2 sigorta şirketi ile veri anlaşması", targetAmount: 55000, completed: false, date: "2026-12-01" },
    ],
  },
  {
    id: "11",
    slug: "defreelance",
    name: "DeFreelance",
    tagline: "Freelancer ve işveren arasında güvenli escrow ile çalışan merkeziyetsiz iş platformu",
    description: "DeFreelance, freelancer ekonomisini Stellar ağına taşıyor. İş anlaşmaları akıllı kontratlara yazılıyor, ödeme milestone bazlı escrow'da tutuluyor. Anlaşmazlıklar DAO yönetimiyle çözülüyor.",
    howItWorks: "İşveren projeyi tanımlayıp bütçeyi escrow'a kilitliyor. Freelancer göreve başvuruyor, anlaşma sağlandıktan sonra çalışmaya başlıyor. Her teslimatta müşteri onayı gelince kilitli fon serbest bırakılıyor. Freelancer portföyü blockchain'de doğrulanabilir hale geliyor.",
    category: "SaaS",
    emoji: "💼",
    coverImage: "/covers/defreelance.jpg",
    raised: 43200,
    goal: 70000,
    backers: 167,
    daysLeft: 11,
    featured: true,
    owner: "GDFL...PP66",
    tags: ["Freelance", "Escrow", "Web3Jobs"],
    createdAt: "2026-08-28",
    team: [
      { name: "Oğuz Türk", role: "Founder & CEO", avatar: "OT" },
      { name: "Beliz Arslan", role: "UX Designer", avatar: "BA" },
      { name: "Emre Koç", role: "Solidity & Soroban Dev", avatar: "EK" },
    ],
    milestones: [
      { id: "m1", title: "Escrow Kontrat", description: "Milestone bazlı ödeme akıllı kontratı", targetAmount: 20000, completed: true, date: "2026-09-01" },
      { id: "m2", title: "Dispute DAO", description: "Anlaşmazlık çözüm mekanizması", targetAmount: 45000, completed: false, date: "2026-10-10" },
      { id: "m3", title: "Mobil Uygulama", description: "iOS & Android lansmanı", targetAmount: 70000, completed: false, date: "2026-11-30" },
    ],
  },
  {
    id: "12",
    slug: "tokenized-art",
    name: "ArtVault",
    tagline: "Türk çağdaş sanatçılarının eserlerini fraksiyonel NFT'lerle yatırıma açan platform",
    description: "ArtVault, pahalı sanat eserlerini küçük paylara bölerek her yatırımcının erişebilmesini sağlıyor. Bir tablonun 1/1000'ine sahip olabiliyorsunuz. Eser değer kazandıkça tüm pay sahipleri kazanıyor.",
    howItWorks: "Sanatçı veya galeri eserini platforma getiriyor. Değerleme uzmanı fiyat belirliyor. Eser 1000 eşit paya bölünüp NFT olarak satışa çıkıyor. Eser fiziksel olarak güvenli depoda saklanıyor. Yılda bir kez açık arttırmada tüm pay sahiplerinin oyuyla satış kararı alınabiliyor.",
    category: "SaaS",
    emoji: "🎨",
    coverImage: "/covers/artvault.jpg",
    raised: 67000,
    goal: 90000,
    backers: 289,
    daysLeft: 8,
    featured: false,
    owner: "GARV...SS11",
    tags: ["Art", "Fractional", "NFT"],
    createdAt: "2026-08-15",
    team: [
      { name: "Simge Özkan", role: "Art Curator & CEO", avatar: "SÖ" },
      { name: "Tarık Yıldız", role: "Blockchain Architect", avatar: "TY" },
    ],
    milestones: [
      { id: "m1", title: "Hukuki Çerçeve", description: "SPK uyumlu fraksiyonel sahiplik modeli", targetAmount: 30000, completed: true, date: "2026-08-20" },
      { id: "m2", title: "İlk Koleksiyon", description: "10 değerli eser tokenizasyonu", targetAmount: 60000, completed: true, date: "2026-09-05" },
      { id: "m3", title: "Galeri Ortaklıkları", description: "İstanbul galeri ağı entegrasyonu", targetAmount: 90000, completed: false, date: "2026-10-30" },
    ],
  },
  {
    id: "13",
    slug: "supplyflo",
    name: "SupplyFlo",
    tagline: "KOBİ tedarik zincirini şeffaflaştıran blockchain tabanlı takip sistemi",
    description: "SupplyFlo, küçük ölçekli üreticilerin tedarik zincirini uçtan uca takip etmesini sağlıyor. Ürün kökeni doğrulanabiliyor, sahte ürün sorunu ortadan kalkıyor. B2B ödemeler Stellar üzerinden otomatik yapılıyor.",
    howItWorks: "Her ürün üretim aşamasında QR kod veya RFID etiketiyle sisteme kaydediliyor. Depo, taşıyıcı ve perakendeci her aşamada blockchain'e kayıt ekliyor. Müşteri ürünün tüm yolculuğunu QR okutarak görebiliyor. B2B ödemeler teslimat onayıyla otomatik tetikleniyor.",
    category: "SaaS",
    emoji: "📦",
    coverImage: "/covers/supplyflo.jpg",
    raised: 16700,
    goal: 50000,
    backers: 52,
    daysLeft: 40,
    featured: false,
    owner: "GSPL...RR55",
    tags: ["SupplyChain", "Traceability", "B2B"],
    createdAt: "2026-09-11",
    team: [
      { name: "Mustafa Demir", role: "CEO & Logistics Expert", avatar: "MD" },
      { name: "Lale Çelik", role: "IoT Engineer", avatar: "LÇ" },
      { name: "Volkan Yılmaz", role: "Full-stack Developer", avatar: "VY" },
    ],
    milestones: [
      { id: "m1", title: "QR Protokolü", description: "Ürün takip standart şeması", targetAmount: 15000, completed: false, date: "2026-10-01" },
      { id: "m2", title: "Pilot Fabrika", description: "3 KOBİ ile pilot entegrasyon", targetAmount: 30000, completed: false, date: "2026-11-01" },
      { id: "m3", title: "Perakende Zinciri", description: "Büyük market zinciri ortaklığı", targetAmount: 50000, completed: false, date: "2026-12-20" },
    ],
  },
  {
    id: "14",
    slug: "votex-dao",
    name: "VoteX DAO",
    tagline: "Üniversite öğrenci konseyi seçimlerini şeffaf blockchain oylamasına taşıyan platform",
    description: "VoteX DAO, öğrenci konseyi seçimlerini manipülasyona karşı koruyor. Her öğrenci anonim oy kullanıyor, sonuçlar anlık görülebiliyor. Seçim organizasyonu haftalardan günlere iniyor.",
    howItWorks: "Üniversite öğrenci kimlik doğrulama sistemine entegre olunuyor. Her öğrenci tek kullanımlık oy token'ı alıyor. Oy kullanılıyor, kimlik gizli kalırken oy geçerliliği kanıtlanabiliyor (zero-knowledge proof). Sonuçlar anlık sayılıyor, herkes doğrulayabiliyor.",
    category: "SaaS",
    emoji: "🗳️",
    coverImage: "/covers/votex.jpg",
    raised: 5800,
    goal: 25000,
    backers: 34,
    daysLeft: 55,
    featured: false,
    owner: "GVTX...NN88",
    tags: ["Voting", "Governance", "University"],
    createdAt: "2026-09-13",
    team: [
      { name: "Alp Öztürk", role: "Co-founder", avatar: "AO" },
      { name: "Rüya Kılıç", role: "Cryptographer", avatar: "RK" },
    ],
    milestones: [
      { id: "m1", title: "ZK Proof Modülü", description: "Anonim oy kanıtlama sistemi", targetAmount: 10000, completed: false, date: "2026-10-15" },
      { id: "m2", title: "Üniversite Pilotu", description: "1 üniversitede gerçek seçim", targetAmount: 18000, completed: false, date: "2026-11-15" },
      { id: "m3", title: "Ulusal Platform", description: "YÖK ile entegrasyon görüşmesi", targetAmount: 25000, completed: false, date: "2027-01-15" },
    ],
  },
  {
    id: "15",
    slug: "microinsure",
    name: "MicroInsure",
    tagline: "Gig ekonomisi çalışanlarına parametrik sigorta sunan merkeziyetsiz platform",
    description: "MicroInsure, kurye, Uber sürücüsü ve diğer gig çalışanlarına uygun fiyatlı mikro sigorta sunuyor. Hasar anında manuel başvuru gerekmeden akıllı kontrat otomatik ödeme yapıyor.",
    howItWorks: "Çalışan çalışmak istediği gün için günlük sigorta satın alıyor (0.5-2 USDC). Kaza veya hastalık durumunda platform doğruluyor; sağlık verisini veya kaza raporunu akıllı kontratlara sunuyor. Koşullar sağlandığında tazminat anında USDC olarak ödeniyor. Sigorta havuzu yatırımcılar tarafından fonlanıyor, hasar oranına göre getiri değişiyor.",
    category: "DeFi",
    emoji: "🛡️",
    coverImage: "/covers/microinsure.jpg",
    raised: 48200,
    goal: 80000,
    backers: 231,
    daysLeft: 16,
    featured: true,
    owner: "GMIC...FF99",
    tags: ["Insurance", "GigEconomy", "DeFi"],
    createdAt: "2026-08-22",
    team: [
      { name: "Sibel Kara", role: "CEO & Actuary", avatar: "SK" },
      { name: "Doruk Aydın", role: "Smart Contract Dev", avatar: "DA" },
      { name: "Pınar Yıldız", role: "Risk Analyst", avatar: "PY" },
    ],
    milestones: [
      { id: "m1", title: "Parametrik Model", description: "Otomatik hasar tetikleyici sistemi", targetAmount: 25000, completed: true, date: "2026-09-01" },
      { id: "m2", title: "Sigorta Havuzu", description: "Likidite sağlayıcı mekanizması", targetAmount: 50000, completed: false, date: "2026-10-01" },
      { id: "m3", title: "SEDDK Onayı", description: "Sigorta düzenleyici kurum lisansı", targetAmount: 80000, completed: false, date: "2026-12-01" },
    ],
  },
];
